
#PSQL = psql $(DB)
# DB = heroku pg:psql
DB = -d tiger
HEROKU = postgres://qllufmrlpjjoom:QUrv1bd2dEn6wU5SFipP7EL5xB@ec2-54-225-103-9.compute-1.amazonaws.com:5432/d584tj8u3bfgga

#tiger line census name
#NYC = 36061
#MESA = 04013
# TIGERID = 36061

#place id for city boundary data
# Mesa: 16000US0446000
# NYC: 16000US3651000
# PLACEID = 16000US3651000

# make database PSQL="heroku pg:psql"

database: db_dev_drop db_dev_create tables

tables: db_roads db_roadnames db_boundaries db_group_union

# database_stage:
	# make DB=$(HEROKU) _database_heroku

# _database_heroku: db_stage_drop tables

#pg_dump -Fc --no-acl --no-owner -h localhost tiger > tiger.dump
#HEROKU_POSTGRESQL_MAGENTA
database_push: database
	 heroku pg:reset --confirm findlines-staging DATABASE_URL
	 heroku pg:push tiger DATABASE_URL --app findlines-staging

# psql $(DB) -q -f roads.sql
# psql $(DB) -q -f roadnames.sql
# # ogr2ogr -f "PostgreSQL" PG:"host=localhost dbname=tiger" "http://services2.arcgis.com/1gVyYKfYgW5Nxb1V/ArcGIS/rest/services/MesaAzCouncilDistricts/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&f=json" OGRGeoJSON -nln "mesa_boundaries" -t_srs "EPSG:4269"
# psql $(DB) -q -f mesa_boundaries.sql
# psql $(DB) -a -f postgis_union_length.sql

# TODO: Handle drop/create differently on heroku than localhost.

db_dev_drop:
	psql -c "DROP DATABASE IF EXISTS tiger"
	psql -c "DROP EXTENSION IF EXISTS postgis"

db_stage_drop:
	 heroku pg:reset --confirm findlines-staging DATABASE_URL

db_dev_create:
	psql -c "CREATE DATABASE tiger" #createdb tiger
	psql $(DB) -c "CREATE EXTENSION postgis;"

db_stage_create:
	# nothing to do here.

db_roads: edges/${TIGERID}.sql
	psql $(DB) -q -f edges/${TIGERID}.sql

db_roadnames: names/${TIGERID}.sql
	psql $(DB) -q -f names/${TIGERID}.sql

db_boundaries: boundaries/${PLACEID}.sql
	psql $(DB) -q -f boundaries/${PLACEID}.sql

db_group_union:
	cat data/union_group.sql | sed -e "s/placetableid/b${PLACEID}/" -e "s/nameid/n${TIGERID}/" -e "s/edgeid/e${TIGERID}/"| psql $(DB) -a

#tiger line census name
#NYC = 36061

edges/tl_2013_${TIGERID}_edges2.shp:
	wget -P edges/ ftp://ftp2.census.gov/geo/tiger/TIGER2013/EDGES/tl_2013_${TIGERID}_edges.zip
	unzip -d edges/ edges/tl_2013_${TIGERID}_edges.zip
	SHAPE_ENCODING="ISO-8859-1" && ogr2ogr edges/tl_2013_${TIGERID}_edges2.shp edges/tl_2013_${TIGERID}_edges.shp -lco ENCODING=UTF-8

edges/${TIGERID}.sql: edges/tl_2013_${TIGERID}_edges2.shp
	shp2pgsql -D -W "LATIN1" -s 4269 edges/tl_2013_${TIGERID}_edges2.shp e${TIGERID} > edges/${TIGERID}.sql

#get county feature names from us census:
names/tl_2013_${TIGERID}_featnames.dbf:
	wget -P names/ ftp://ftp2.census.gov/geo/tiger/TIGER2013/FEATNAMES/tl_2013_${TIGERID}_featnames.zip
	unzip -d names/ names/tl_2013_${TIGERID}_featnames.zip


names/${TIGERID}.sql: names/tl_2013_${TIGERID}_featnames.dbf
	@echo "You can ignore the following notice about a missing tl_2013_${TIGERID}_featnames.shp; we don't need it"
	shp2pgsql -D -W "LATIN1" -s 4269 names/tl_2013_${TIGERID}_featnames n${TIGERID} > names/${TIGERID}.sql

boundaries/${PLACEID}.sql:
	rm -f boundaries/${PLACEID}.shp #in case it existed already
	# ogr2ogr -f 'ESRI Shapefile' mesa_boundaries.shp "http://services2.arcgis.com/1gVyYKfYgW5Nxb1V/ArcGIS/rest/services/MesaAzCouncilDistricts/FeatureServer/2/query?where=objectid+%3D+objectid&outfields=*&f=json" OGRGeoJSON
	mkdir -p boundaries/
	ogr2ogr -f 'ESRI Shapefile' boundaries/${PLACEID}.shp "http://api.censusreporter.org/1.0/geo/tiger2012/$(PLACEID)?geom=true" -skipfailures
	shp2pgsql -D -W "LATIN1" -s 4269 boundaries/${PLACEID}.shp b${PLACEID} > boundaries/${PLACEID}.sql

clean:
	git ls-files -o | xargs rm
